spring:
  data:
    mongodb:
      
      uri: ${MONGODB_URI:mongodb://localhost:27017/fitnessactivity}
  rabbitmq:
    # Use the full URL provided by CloudAMQP

    host: localhost
    port: 5672
    username: guest
    password: guest
  ##  port: ${RABBITMQ_PORT:5672}


server:
  port: ${PORT:8082}


eureka:
  client:
    serviceUrl:

      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

