server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/fitnessmicroservice-f8902
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service    # Changed from lb:// to direct HTTP IP
          predicates:
            - Path=/api/users/**

        - id: activity-service
          uri: lb://activity-service         # Assuming you still want Eureka for these
          predicates:
            - Path=/api/activities/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/recommendations/**
